username = input("Имя пользователя: ")
print(username)
title = input("Заголовок заметки: ")
print(title)
content = input("Описание заметки: ")
print(content)
status = input("Статус заметки: ")
print(status)
created_date = input("Дата создания заметки (dd-mm-yyyy): ")
print(created_date )
issue_date = input("Дата истечения заметки (dd-mm-yyyy): ")
print(issue_date)
